VirtualWallet.WebApp/Controllers/SpendingController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VirtualWallet.ApiConsumer.Interfaces;
using VirtualWallet.DAL.Services.Interfaces;
using VirtualWallet.Model.Domain;
using VirtualWallet.Common.Extensions;

namespace VirtualWallet.WebApp.Controllers
{
    public class SpendingController : BaseController
    {
        private readonly ISpendingApiConsumer _spendingApiConsumer;
        private readonly IMonthlySpendingApiConsumer _monthlySpendingApiConsumer;
        public SpendingController(IUserContainer userContainer, IUserApiConsumer userApiConsumer,
            ISpendingApiConsumer spendingApiConsumer, IMonthlySpendingApiConsumer monthlySpendingApiConsumer) : base(userContainer, userApiConsumer)
        {
            _spendingApiConsumer = spendingApiConsumer;
            _monthlySpendingApiConsumer = monthlySpendingApiConsumer;
        }

        // GET: SpendingController
        public ActionResult Index()
        {
            return View();
        }

        // GET: SpendingController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SpendingController/Create
        public ActionResult Create(int month, int year)
        {
            ViewBag.Month = month;
            ViewBag.Year = year;
            return View();
        }

        // POST: SpendingController/Create
        [HttpPost]
        public ActionResult Create(Spending spending)
        {
            // TODO: Add validation

            var currentUser = _userContainer.GetCurrentUser();
            var currentSpendingGroup = _userContainer.GetCurrentSpendingGroup();

            spending.User = currentUser;
            var date = DateTime.Parse(Request.Form["date-picker"]);
            spending.CreationDate = date;

            var currentMonthlySpending = _monthlySpendingApiConsumer.GetByMonthAndYear(currentSpendingGroup.Id, date.Month, date.Year);
            spending.MonthlySpending = currentMonthlySpending;
            var justAddedSpending = _spendingApiConsumer.Insert(spending);

            return RedirectToAction("Current", "MonthlySpending" , new { dateTime = new DateTime(date.Year, date.Month, 1) });
        }

        // POST: SpendingController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: SpendingController/Edit/5

        [HttpGet]
        public ActionResult Edit(int id, int month, int year)
        {
            var spending = _spendingApiConsumer.GetOneById(id);
            return View(spending);
        }
        [HttpPost]
        public ActionResult Edit(Spending spending)
        {
            var monthlySpendingId = int.Parse(Request.Form["monthly-spending-id"]);
            var monthlySpending = _monthlySpendingApiConsumer.GetOneById(monthlySpendingId);
            spending.MonthlySpending = monthlySpending;
            spending.User = _userContainer.GetCurrentUser();

            var valueIsDecimal = decimal.TryParse(Request.Form["money-value"].ToString()?.Replace(".", ",") ?? "0", out var value);
            if (!valueIsDecimal)
            {
                ModelState.AddModelError("1", "Podana wartość nie jest liczbą");
            }
            spending.Value = value;

            if (!ModelState.IsValid)
            {
                return View(spending);
            }
            _spendingApiConsumer.Update(spending);
            var month = spending.CreationDate.Value.Month;
            var year = spending.CreationDate.Value.Year;
            return RedirectToAction("Current", "MonthlySpending", new { dateTime = new DateTime(year, month, 1) }); 
        }

        // POST: SpendingController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: SpendingController/Delete/5
        public ActionResult Delete(int id, int month, int year)
        {
            _spendingApiConsumer.Delete(id);
            return RedirectToAction("Current", "MonthlySpending", new { dateTime = new DateTime(year, month, 1) });
        }

    }
}

VirtualWallet.WebApp/Views/Spending/Create.cshtml
@model VirtualWallet.Model.Domain.Spending

@{
    ViewData["Title"] = "Create";
}

@{
    var defaultDate = new DateTime(ViewBag.Year, ViewBag.Month, DateTime.Now.Day);
}

<h1>Nowy Wydatek</h1>

<h4>Dodawanie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Spending" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <label class="control-label">(Domyślnie: @defaultDate.ToString("dd.MM.yyyy"))</label>
                <input name="date-picker" type="date" class="form-control" value="@defaultDate.ToString("yyyy-MM-dd")" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="submit-btn" type="submit" value="Utwórz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Current" asp-controller="MonthlySpending">Powrot</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
    </script>
}

VirtualWallet.WebApp/Views/Spending/Edit.cshtml
@model VirtualWallet.Model.Domain.Spending

@{
    ViewData["Title"] = "Edit";
}

<h1>Edycja wydatku</h1>

<hr />
<span class="text-danger">@Html.ValidationSummary()</span>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                @*<input asp-for="Value" class="form-control"  />*@
                <input name="money-value" class="form-control" value="@Model.Value" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="CreationDate" class="form-control" type="hidden" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="User" class="form-control" type="hidden" />
                <span asp-validation-for="User" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="MonthlySpending" class="form-control" type="hidden" />
                <span asp-validation-for="MonthlySpending" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="form-control" type="hidden" name="monthly-spending-id" value="@Model.MonthlySpending.Id" />
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz zmiany" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Current" asp-controller="MonthlySpending">Powrót</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}