VirtualWallet.WebApp/Controllers/SpendingGroupController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VirtualWallet.ApiConsumer.Interfaces;
using VirtualWallet.DAL.Services.Interfaces;
using VirtualWallet.Model.Domain;

namespace VirtualWallet.WebApp.Controllers
{
    public class SpendingGroupController : BaseController
    {
        private readonly ISpendingGroupApiConsumer _spendingGroupApiConsumer;

        public SpendingGroupController(IUserContainer userContainer, IUserApiConsumer userApiConsumer, 
            ISpendingGroupApiConsumer spendingGroupApiConsumer) : base(userContainer, userApiConsumer)
        {
            _spendingGroupApiConsumer = spendingGroupApiConsumer;
        }

        // GET: UserSpendingGroupController
        public ActionResult Index(User user)
        {
            var spendingGroups = _spendingGroupApiConsumer.GetForUser(user.Id);
            return View(spendingGroups);
        }

        public ActionResult Pick(int spendingGroupId)
        {
            // TODO: Make sure that picked sepnding group is for current user
            var pickedSpendingGroup = _spendingGroupApiConsumer.GetOneById(spendingGroupId);
            _userContainer.SetSpendingGroup(pickedSpendingGroup);
            return RedirectToAction("Index", "Home");
        }

        // GET: UserSpendingGroupController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UserSpendingGroupController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserSpendingGroupController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserSpendingGroupController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserSpendingGroupController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserSpendingGroupController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserSpendingGroupController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

VirtualWallet.WebApp/Views/SpendingGroup/Create.cshtml
@model VirtualWallet.Model.Domain.SpendingGroup

@{
    ViewData["Title"] = "Create";
}

<h1>Tworzenie nowej grupy wydatków</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Utwórz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wróć</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VirtualWallet.WebApp/Views/SpendingGroup/Index.cshtml
@using VirtualWallet.Common.Extensions 
@model IEnumerable<VirtualWallet.Model.Domain.SpendingGroup>

@{
    ViewData["Title"] = "Index";
}

<h1>Wybierz grupę wydatków</h1>

<p>
    <a asp-action="Create">Nowa</a>
</p>

@{
    if (Model.IsNotNullOrEmpty())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Budget)
                    </th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Budget)
                        </td>
                        <td>
                            @Html.ActionLink("Edytuj", "Edit", new { /* id=item.PrimaryKey */ }) |
                            @Html.ActionLink("Szczegóły", "Details", new { /* id=item.PrimaryKey */ }) |
                            @Html.ActionLink("Usuń", "Delete", new { /* id=item.PrimaryKey */ })
                        </td>
                        <td>
                            <strong>@Html.ActionLink("Wybierz", "Pick", "SpendingGroup", new { spendingGroupId = item.Id }, new { @class = "btn btn-primary" })</strong>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h2>Brak danych</h2>
    }
}